Social/config/routes.rb
Social::Application.routes.draw do

  resources :users do
    collection do
      get 'reset'
      post 'request_password_reset'
      get 'reset_password'
    end
  end
  resource :session
  resources :friend_circles
  resources :posts

end

Social/app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :name, :member_ids

  validates :name, presence: true

  has_many(
    :memberships,
    :class_name => "FriendCircleMembership",
    :foreign_key => :friend_circle_id,
    :primary_key => :id
  )

  has_many(
    :members,
    through: :memberships,
    source: :user
  )

  has_many(
    :post_shares,
    class_name: "PostShare",
    foreign_key: :circle_id,
    primary_key: :id,
    inverse_of: :circle
  )

end

Social/app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :user_id, :friend_circle_id

  validates :user_id, :friend_circle_id, presence: true

  belongs_to(
    :user,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  belongs_to(
    :friend_circle,
    :class_name => "FriendCircle",
    :foreign_key => :friend_circle_id,
    :primary_key => :id
  )

end

Social/app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :post_id

  validates :url, :post, presence: true

  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :links
  )

end

Social/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :user_id, :body, :circle_ids

  validates :user_id, :body, presence: true

  has_many(
    :links,
    class_name: "Link",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post
  )

  has_many(
    :post_shares,
    class_name: "PostShare",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post
  )

  has_many(
    :circles,
    through: :post_shares,
    source: :circle
  )
end

Social/app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :circle_id, :post_id

  validates :post_id, :circle_id, presence: true

  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post_shares
  )

  belongs_to(
    :circle,
    class_name: "FriendCircle",
    foreign_key: :circle_id,
    primary_key: :id,
    inverse_of: :post_shares
  )

end

Social/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :session_token, :password_token

  validates :email, :password_digest, :session_token, presence: true
  before_validation :ensure_session_token


  has_many(
    :memberships,
    :class_name => "FriendCircleMembership",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  has_many(
    :circles,
    through: :memberships,
    source: :friend_circle
  )


  def password=(password)
    self.password_digest = BCrypt::Password.create(password) unless password.blank?
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end


  def set_password_token
    self.password_token = SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= self.reset_session_token
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by_email(email)

    if !@user.nil? && @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def reset_session_token
    self.session_token = User.generate_session_token
  end

end

Social/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper
  protect_from_forgery
end

Social/app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def new
    @cirlce = FriendCircle.new
  end

  def create
    @circle = FriendCircle.new(params[:friend_circle])

    if @circle.save
      render :json => @circle
    else
      flash[:errors] = @circle.errors.full_messages
      render :new
    end
  end

  def edit
    @circle = FriendCircle.find(params[:id])
  end

  def update
    @circle = FriendCircle.find_by_id(params[:id])

    if @circle.update_attributes(params[:friend_circle])
      render :json => @circle
    else
      flash[:errors] = @circle.errors.full_messages
      render :edit
    end
  end
end

Social/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new

  end

  def create
    @post = Post.new(params[:post])
    params[:link].each do |link|
      @post.links.new(url: link) unless link.empty?
    end

    if @post.save
      render :json => @post
    else
      render :json => @post.errors.full_messages

    end
  end

end

Social/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      log_in!(@user)
      redirect_to new_session_url
    else
      render :text => "Wrong Credentials"
    end
  end

  def destroy
    log_out!
    if current_user.save
      redirect_to new_session_url
    else
      render :text => "Log out fail!"
    end
  end


end

Social/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])

    if @user.save
      render :text => "#{@user} saved"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end


  def reset_password
    @user = User.find(params[:id])
    if @user.password_token == params[:password_token]
      render :reset_password
    else
      flash[:errors] = ["Inaccurate link"]
      redirect_to reset_users_url
    end
  end


  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank?
      flash[:errors] = ["Password can't be blank"]
      redirect_to reset_password_users_url(params[:email_params])
    else
      @user.update_attributes(params[:user])
      @user.password_token = nil
      @user.save
      render :json => @user
    end
  end

  def request_password_reset
    @user = User.find_by_email(params[:user][:email])

    if @user
      send_reset_email(@user)

      flash[:errors] = ["Email Sent"]
      redirect_to reset_users_url
    else
      flash[:errors] = ["No such email"]
      redirect_to reset_users_url
    end
  end

  def reset
    render :reset
  end


end

Social/app/helpers/application_helper.rb
module ApplicationHelper
end

Social/app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

Social/app/helpers/posts_helper.rb
module PostsHelper
end

Social/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in!(user)
    session[:token] = user.session_token
    current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def current_user=(user)
    @current_user = user
  end

  def log_out!
    current_user.reset_session_token
    session[:token] = nil
    # current_user.save!
  end
end

Social/app/helpers/users_helper.rb
module UsersHelper

  def send_reset_email(user)
    user.set_password_token
    user.save!
    msg = UserMailer.reset_email(user)
    msg.deliver!
  end
end

Social/app/views/friend_circles/_form.html.erb
<% action_url = @circle.persisted? ? friend_circle_url : friend_circles_url %>

<form action="<%=action_url%>" method="post">

  <% if @circle.persisted? %>
    <input type="hidden" name="_method" value="put">
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">


  <label id="friend_circle_name">New Friend Circle</label>
  <input type="text" name="friend_circle[name]" id="friend_circle_name" value="<%= @circle.name %>">
  <p>


  <% User.all.each do |user| %>
       <% html_id = "user_circle_ids_#{user.id}" %>
       <input
         type="checkbox"
         name="friend_circle[member_ids][]"
         value="<%= user.id %>"
         id="<%= html_id %>"
         <%= "checked" if @circle.members.include?(user) %>
         >
       <label for="<%= html_id %>">
         <%= user.email %>
       </label><br>
     <% end %>
   <p>

     <input type="hidden" name="friend_circle[member_ids][]" value="">


  <input type="submit" name="Submit">
</form>

Social/app/views/friend_circles/edit.html.erb
<%= render :partial => "form" %>

Social/app/views/friend_circles/new.html.erb
<form action="<%=friend_circles_url%>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">


  <label id="friend_circle_name">New Friend Circle</label>
  <input type="text" name="friend_circle[name]" id="friend_circle_name">
  <p>


  <% User.all.each do |user| %>
    <% if current_user.id == user.id%>
    <input type="hidden" name="friend_circle[member_ids][]" value="<%= user.id %>">
    <% else %>
       <% html_id = "user_circle_ids_#{user.id}" %>
       <input
         type="checkbox"
         name="friend_circle[member_ids][]"
         value="<%= user.id %>"
         id="<%= html_id %>">
       <label for="<%= html_id %>">
         <%= user.email %>
       </label><br>
     <% end %>
   <% end %>
   <p>


  <input type="submit" name="Submit">
</form>

Social/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

<% if current_user.nil? %>
<%= button_to "Log in", new_session_url, method: :get %>
<% else %>
<%= button_to "Log out", session_url, method: :delete %>
<%= current_user.email %>
<% end %>


<%= yield %>

</body>
</html>

Social/app/views/posts/new.html.erb
<form action="<%=posts_url%>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

   <input type="hidden" name="post[user_id]" value="<%=current_user.id%>">
  <label for="post_body">Describe Links</label><br>
  <textarea name="post[body]" id="post_body"></textarea>
  <p>


  <% FriendCircle.all.each do |circle| %>

       <% html_id = "circle_ids_#{circle.id}" %>
       <input
         type="checkbox"
         name="post[circle_ids][]"
         value="<%= circle.id %>"
         id="<%= html_id %>">
       <label for="<%= html_id %>">
         <%= circle.name %>
       </label><br>
     <% end %>

   <p>

     <% 3.times do |t| %>

     <label for="link<%=t%>">Link <%=t+1%></label>
     <input type="text" name="link[]" id="link<%=t%>"><br>

     <% end %>
  <input type="submit" name="Submit">
</form>

Social/app/views/users/new.html.erb
<form action="<%=users_url%>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">


  <label id="user_email">Email</label>
  <input type="text" name="user[email]" id="user_email">

  <label id="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">

  <input type="submit" name="Submit">

</form>

Social/app/views/users/reset.html.erb
<form action="<%= request_password_reset_users_url %>", method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">


<label id="user_email">Email</label>
<input type="text" name="user[email]" id="user_email">

<input type="submit" name="Submit">
</form>

Social/app/views/users/reset_password.html.erb
<form action="<%= user_path(params[:id]) %>", method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">


  <input  type="hidden" name="_method" value="put">
<label id="new_password">Password</label>
<input type="text" name="user[password]" id="new_password">

<input type="hidden" name="email_params[password_token]" value="<%=params[:password_token]%>">
<input type="hidden" name="email_params[id]" value="<%=params[:id]%>">

<input type="submit" name="Submit">


</form>